# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyredis < Formula
  desc "Lazygit-inspired terminal UI for Redis"
  homepage "https://github.com/sm010422/lazyredis"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sm010422/lazyredis/releases/download/v0.4.0/lazyredis_darwin_amd64.tar.gz"
      sha256 "162391f6ee0e5a6022da1ce42b60841c53e4c6c28b313ebcc1f952c138698711"

      define_method(:install) do
        bin.install "lazyredis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sm010422/lazyredis/releases/download/v0.4.0/lazyredis_darwin_arm64.tar.gz"
      sha256 "b13e6b144f79f38ba7be82a425e7498c1d30b3bdda6842746d19db79a4dd76b8"

      define_method(:install) do
        bin.install "lazyredis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sm010422/lazyredis/releases/download/v0.4.0/lazyredis_linux_amd64.tar.gz"
      sha256 "99627589c954caf19774e1d957e423908c37eae63f141e4771a257aea8a0af0a"
      define_method(:install) do
        bin.install "lazyredis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sm010422/lazyredis/releases/download/v0.4.0/lazyredis_linux_arm64.tar.gz"
      sha256 "df4a09bdf05dc1690e48eee6d58ec0fe60fd70903ffc3716dd44737f243aaa03"
      define_method(:install) do
        bin.install "lazyredis"
      end
    end
  end

  test do
    assert_predicate bin/"lazyredis", :exist?
  end
end
